version: '3.8'

services:
  webapplication:
    image: webapplication:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./logs:/app/logs
    restart: always

  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

  webapplication1-1:
    image: webapplication1-1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
