version: '3.8'
services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: MyUser
      POSTGRES_PASSWORD: MyPassword
      POSTGRES_DB: MyDatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U MyUser -d MyDatabase || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  webapplication1:
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
      args:
        BUILD_CONFIGURATION: Release

    ports:
      - "80:80"

    environment:
      ASPNETCORE_URLS: "http://+:80"

    depends_on:
      - db

volumes:
  db_data: