version: '3.8'
services:
  db:
    image: postgres:17
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_USER=MyUser
      - POSTGRES_PASSWORD=MyPassword
      - POSTGRES_DB=MyDatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U MyUser -d MyDatabase || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  webapplication1:
    image: apiapp:1.2
    ports:
      - "80:80"
    environment:
      - DefaultConnection=Host=db;Port=5432;Database=MyDatabase;Username=MyUser;Password=MyPassword
      - ASPNETCORE_URLS="http://+:80"
    
    depends_on:
      - db
    
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  db_data: