version: '3.8'
services:
  webapplication1:
    container_name: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
      args:
        BUILD_CONFIGURATION: Release

    ports:
      - "80:80"

    environment:
      ASPNETCORE_URLS: "http://+:80"

    restart: unless-stopped