version: '3.8'
services:
  webapplication1:
    image: api_app_stack:latest
    ports:
      - "80:80"
    secrets:
      - DefaultConnection
    deploy:
      restart_policy:
        condition: on-failure

secrets:
  DefaultConnection:
    external: true
